import CssBaseline from '@mui/material/CssBaseline';

export const metadata = {
  title: "Statut d'occupation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <CssBaseline />
        <body>{children}</body>
    </html>
  );
}
